spring.application.name=order-service

# AWS LocalStack Configuration
spring.cloud.aws.region.static=us-east-1
spring.cloud.aws.credentials.access-key=test
spring.cloud.aws.credentials.secret-key=test
spring.cloud.aws.sns.endpoint=http://localhost:4566

# SNS Topic
sns.topic.name=order-events-topic