spring.application.name=order-service

# RabbitMQ connection
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# RabbitMQ specific settings
spring.rabbitmq.connection-timeout=30000
spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true

rabbitmq.exchange.name=order_exchange

rabbitmq.queue.stock.name=stock
rabbitmq.binding.stock.routing.key=stock_routing_key

rabbitmq.queue.email.name=email
rabbitmq.binding.email.routing.key=email_routing_key

logging.level.org.springframework.amqp=DEBUG
logging.level.com.rabbitmq.client=DEBUG