spring.application.name=email-service
server.port=8082

# AWS LocalStack Configuration
spring.cloud.aws.region.static=us-east-1
spring.cloud.aws.credentials.access-key=test
spring.cloud.aws.credentials.secret-key=test
spring.cloud.aws.sqs.endpoint=http://localhost:4566

# SQS Queue
sqs.queue.email=email-queue